# Generated by Django 3.2.4 on 2021-06-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210626_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_w',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
